### ISSUE TITLE
训练过程中 cvloss 与 stloss 不收敛

### ISSUE THREAD

**Issue by csustYyh** [wenguanwang/VOS_Correspondence#2]
您好，感谢您这项工作同时还开源了代码，这使我在自己的研究工作上受益匪浅。
我在复现这项工作训练过程中发现 cvloss 与 stloss 不收敛，请问您在实验过程中有遇到这种情况吗？

p.s. 我只进行主训练，没有在静态数据集上训练

前 200 次训练:
![image](https://github.com/wenguanwang/VOS_Correspondence/assets/118873316/1b3e97a5-5635-44d5-8925-564ab9748a51)

第 10000 次： cvloss 与 stloss 没有明显降低
![image](https://github.com/wenguanwang/VOS_Correspondence/assets/118873316/28021128-7292-4477-be39-c1599021f7be)

第 30100 次： cvloss 与 stloss 为 nan
![image](https://github.com/wenguanwang/VOS_Correspondence/assets/118873316/9b78642d-4459-4ffb-9547-683fda05be4a)

**Comment by lingorX** [comment]
We have indeed encountered this problem. It is caused by the unstable training of L2 similarity under the AMP mode. You can solve it by disabling AMP.

**Comment by csustYyh** [comment]
Thank you for your response！ It's very helpful.
